
    /* Retexturized Objects (Optional) - For remove texture of model, remove "if" or "else if" */

    if(ModelID == -7732) { // Model: wshbuildws10.dff - Rafaels clothing store
        SetDynamicObjectMaterial(objectid, 1, 5819, "buildtestlawn", "lawshopwall4", 0xFF335F3F);
    }
    else if(ModelID == -8158) { // Model: wash_hardwares.dff - Tool building around VCPD

        SetDynamicObjectMaterial(objectid, 0, 12855, "cunte_cop", "sw_brick05", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 1, 6875, "vegasnbuild1", "brickvgn1_128", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 2, 3063, "col_wall1x", "ab_wood1", 0xFFFFFFFF);
    }
    else if(ModelID == -8725) { // Model: od_bighotpool.dff - Pool from back of building, aprox. beach and vcpd
        SetDynamicObjectMaterial(objectid, 0, 3781, "lan2office", "glass_office4", 0xFF105082);
        SetDynamicObjectMaterial(objectid, 1, 13003, "ce_racestart", "sa_wood07_128", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 2, 3741, "cehillhse14", "swimpoolside1_128", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 3, 14806, "bdupshifi", "Bdup2_wood", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 4, 11496, "des_nwstuff", "brdwalkwater_la", 0xFFA3ADC6);
    }
    // Marina Bay
    else if(ModelID == -7765) { // Model: wshbuildws36.dff - Marina Bay - Center Object
        SetDynamicObjectMaterial(objectid, 1, 2591, "ab_partition1", "ab_fabricCheck2", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 3, 8395, "pyramid", "luxorwindow01_128", 0xFF9F9D94);
        SetDynamicObjectMaterial(objectid, 5, 1557, "dave_door_2b", "miragedoor1_256", 0xFFD78E10);
    }
    else if(ModelID == -7819) { // Model: marina2.dff - Marina Bay
        SetDynamicObjectMaterial(objectid, 2, 2591, "ab_partition1", "ab_fabricCheck2", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 3, 8395, "pyramid", "luxorwindow01_128", 0xFF9F9D94);
    }
    else if(ModelID == -7818) { // Model: marina1.dff - Marina Bay
        SetDynamicObjectMaterial(objectid, 1, 2591, "ab_partition1", "ab_fabricCheck2", 0xFFFFFFFF);
        SetDynamicObjectMaterial(objectid, 3, 8395, "pyramid", "luxorwindow01_128", 0xFF9F9D94);
    }
